name: 3D Contribution

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: EngMohammedJoba
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
